%YAML:1.0
---
# 每秒钟更新面部位置的帧数，当处理器性能较低或目标移动较慢时，可以调低（范围：1-30）
FPS: 15
# 距离队列(帧)
DIS_DEQUE: 150
# 面部队列(帧)
FACE_DEQUE: 15
# 移动判别(mm)
MOVE_JUDGE: 25
# 读取指令waitkey时间(ms)
WAIT_TIME: 5
# 电机速度(0-255)
SPEED: 10
# 电机加速度(0-255)
A: 200