%YAML:1.0
---
# ****************面部识别相关*************
# 每秒钟更新面部位置的帧数，当处理器性能较低或目标移动较慢时，可以调低（范围：1-30）
FPS: 10
# 距离队列(帧)
DIS_DEQUE: 150
# 面部队列(帧)
FACE_DEQUE: 15
# 移动判别(mm)
MOVE_JUDGE: 25

# ****************对焦逻辑相关*************
# 掉帧切换目标阈值
MAX_DROP_FRAME: 5
# 掉帧后的处理模式
DROP_PROCESS_MODE: 1

# ****************电机控制相关*************
# 读取指令waitkey时间(ms)
WAIT_TIME: 4
# 电机速度(0-255)
SPEED: 60
# 电机加速度(0-255)
A: 255

# ****************深度相机相关*************
# 相机型号(0:astra/1:realsense)
cam_module: 0
# astra 分辨率
ASTRA_width: 640
ASTRA_height: 480
# realsense 分辨率
RS_width: 1280
RS_height: 720
# realsense 帧率
RS_fps: 30