%YAML:1.0
---
# ****************面部/物体识别相关*************
# 每秒钟更新面部位置的帧数，当处理器性能较低或目标移动较慢时，可以调低（范围：1-30）（60帧时实际值需要*2，以此类推）
FPS: 10
# 距离队列(帧)
DIS_DEQUE: 150
# 最大面部数量
FACE_DEQUE: 10
# 移动判别(mm)
MOVE_JUDGE: 25
# 允许的最小框边长
DRAW_BOX_MIN: 25
# 视场角(镜头等效焦段/mm)(大于24会开启视角限缩)
LENS_LENGTH: 55
# ROI焦距设置(建议大于视场角设置值，必须大于24)
ROI_LENGTH: 75
# width补偿量
width_compensate: 0
# height补偿量
height_compensate: 0


# ****************对焦逻辑相关*************
# 掉帧切换目标阈值
MAX_DROP_FRAME_OBJECT: 10
# 掉帧切换面部阈值
MAX_DROP_FRAME_FACE: 6
# 掉帧后的处理模式(1:中心点对焦/2:中心区域对焦)
DROP_PROCESS_MODE: 2
# 面部确认限制(需要连续识别多少帧才允许新建面部)
FACE_INIT_LIMIT: 3
# 目标确认限制(需要连续识别多少帧才允许新建目标)
TARGET_INIT_LIMIT: 4


# ****************目标匹配逻辑相关*************
# 面部实际距离之比的最大值(越大越宽松)
DIS_RATIO_MAX: 1.35
# 方框面积比例基准系数(越大越宽松)
AREA_RATIO_COEF: 2.0
# 目标点帧间位移基准系数(越小越宽松)
POINT_DIS_COEF: 1.25


# ****************电机控制相关*************
# 读取指令waitkey时间(ms)
WAIT_TIME: 4
# 电机速度(0-255)
SPEED: 20
# 电机加速度(0-255)
A: 255
# 距离滤波器开关(关闭后为FASTEST最快模式，开启后可以调整快慢)（0为关闭，1为开启）
KALMAN_ON: 0
# 距离滤波:kalman-process
KALMAN_PROCESS: 0.01
# 距离滤波:kalman-measure(推荐值0.01:FAST/0.02:NORMAL/0.04:SLOW)
KALMAN_MEASURE: 0.01
# 镜头代号(1/2/3/4/5，设置为0会进入校准模式)
LENS_NUM: 2
# 是否开机自动校准(1:是/2:否)
AUTO_CAL: 1

# ****************深度相机相关*************
# 相机型号(0:astra/1:realsense)
cam_module: 1
# 是否倒置(0:否/1:是)
INVERT_ON: 0
# 是否开启ROI区域(0:否/1:是)(废弃，默认启用)
ROI_ON: 0
# astra 分辨率
ASTRA_width: 640
ASTRA_height: 480
# realsense 分辨率
RS_width: 848
RS_height: 480
# realsense 帧率(建议在低光照环境下降低帧率，否则面部识别容易受到噪点干扰)
RS_fps: 30